---
title: 'Answers for Plotting'
author: "Hao Wang"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# 1. Load essential packages
```{r, message=FALSE}
library(VGAM)
library(car)
library(MASS)
library(effects)
library(ggplot2)
library(Zelig)
library(ZeligChoice)
library(readstata13)
play<- read.dta13('https://github.com/haowang666/POS603-Lab/blob/master/Lab%206/stdSingh.dta?raw=true')
```



# 2. Run Zelig estimates
```{r}
zlogit <- zelig(voted ~severity*age + polinfrel + income + efficacy + partyID +
                  dist_magnitude + enep + vicmarg_dist + 
                  parliamentary + development, model ="logit", data=play, cite = FALSE)
summary(zlogit)
```

## Check Ranges
```{r}
#check range
summary(play$development)
```

## Create data and run simulation
```{r}
#41 Xs
x.sim <- setx(zlogit, development = seq(from = -2, to = 2, by = 0.1))
s.out <- sim(zlogit, x = x.sim)
```

```{r}
#plot(s.out)
ci.plot(s.out, qi ="ev")
```

## If you are unhappy with the default plot...

We need to extract info from zelig simulation
```{r}
## Ranges of values
development = seq(from = -2, to = 2, by = 0.1)

# Extract expected values from simulations
# ev is expected values
phat<- s.out$get_qi(qi='ev', xvalue = 'range')
# collapse list to dataframe
phat <- as.data.frame(matrix(unlist(phat), nrow =1000))
# apply function to column
a<- apply(phat, 2, quantile, probs = c(0.025, 0.975, 0.25, 0.75)) 
low <- a[1,]
high <- a[2,]
qt.1 <- a[3,]
qt.3 <- a[4,]
fit <- apply(phat, 2, mean) 
plotdata <- as.data.frame(cbind(low, high, fit, qt.1, qt.3))
plotdata$development <- development

#in ggplot2
ggplot() +
  geom_line(data = plotdata, aes(x = development, y =fit)) + 
  geom_line(data = plotdata, aes(x = development, y =high), linetype="dashed", color="blue") + 
  geom_line(data = plotdata, aes(x = development, y =low), linetype="dashed", color="blue") + 
  geom_rug(data = play, aes(x= development)) +
  xlab("Level of Development (95% CI)") + 
  ylab("Expected Values E(Y|X)") + 
  ggtitle("Marginal Effect of Development")+
  geom_ribbon(data=plotdata, aes(x=development, ymin=low, ymax=high), alpha=0.2) +
  geom_ribbon(data=plotdata, aes(x=development, ymin=qt.1, ymax=qt.3), alpha=0.6)

```


# 3. Or use vanilla GLM code
```{r, message=FALSE, warning=FALSE}
glm <-  glm(formula = voted ~severity*age + polinfrel + income 
                  + efficacy + partyID +
                  dist_magnitude + enep + vicmarg_dist + 
                  parliamentary + development, 
              data = play, family = binomial(link = "logit"))
development<-seq(-2,2,by=.1)
attach(play)
newdata <- as.data.frame(cbind(1,development,mean(severity),
                            mean(age),mean(polinfrel),mean(income),
                            mean(efficacy),mean(partyID),
                            mean(vicmarg_dist),mean(parliamentary),
                            mean(dist_magnitude),mean(enep)))

colnames(newdata)<-c("constant","development",
                     "severity","age","polinfrel","income",
                     "efficacy","partyID","vicmarg_dist",
                     "parliamentary","dist_magnitude","enep")
#response offers expected value
pr <- predict(glm, newdata = newdata, se.fit=TRUE, type="response")
#what if you missed the command type="reaponse"?
#you get linear prediction results
pr2 <- predict(glm, newdata = newdata)
fit2 <- 1/(1+exp(- pr2))
cor(pr$fit, fit2)
detach(play)
```


## Plot it
```{r}
plotdata <- as.data.frame(pr$fit)
colnames(plotdata)<-c("fit")
plotdata$se <- pr$se.fit
plotdata$low <- plotdata$fit - 1.96*plotdata$se
plotdata$high <- plotdata$fit + 1.96*plotdata$se
plotdata$development <- development

ggplot() +
  geom_line(data = plotdata, aes(x = development, y =fit)) + 
  geom_line(data = plotdata, aes(x = development, y =high), linetype="dashed", color="blue") + 
  geom_line(data = plotdata, aes(x = development, y =low), linetype="dashed", color="blue") + 
  geom_rug(data = play, aes(x= development)) +
  xlab("Level of Development (95% CI)") + 
  ylab("Expected Values E(Y|X)") + 
  ggtitle("Marginal Effect of Development")+
  geom_ribbon(data=plotdata, aes(x=development, ymin=low, ymax=high), alpha=0.5)
```

